version: '3.8'

services:
  web-app:
    # IMPORTANT: Change 'priyanshu' to your actual Docker Hub username in this file
    image: priyanshu/mern-app:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
